name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  release:
    if: github.event.pull_request.merged == true
    
    runs-on: ubuntu-latest
    
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Draft the release
        run: |
          gh release create \
            "${GITHUB_HEAD_REF#release-}" \
            --draft \
            --generate-notes \
            --title "Release ${GITHUB_HEAD_REF#release-}"
