name: Test

# Controls when the action will run. 
on:
  pull_request:
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  scheme: AceLayout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup:
    runs-on: macos-latest
    
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
      - uses: actions/checkout@v2
      
  test_on_macos:
    runs-on: macos-latest
    needs: setup
    
    steps:
      - name: Build for macOS
        run: swift build
        
      - name: Run Tests on macOS
        run: swift test
        
  test_on_ios:
    runs-on: macos-latest
    needs: setup
    
    env:
      IOS_SIMULATOR: "iPhone 13"
    
    steps:
      - name: Build for iOS
        run: xcodebuild build -scheme ${{ env.scheme }} -destination name=${{ env.IOS_SIMULATOR }}
        
      - name: Run Tests on iOS
        run: xcodebuild clean test -scheme ${{ env.scheme }} -destination name=${{ env.IOS_SIMULATOR }}
        
  test_on_tvos:
    runs-on: macos-latest
    needs: setup
    
    env:
      TVOS_SIMULATOR: "Apple TV"
    
    steps:
      - name: Build for tvOS
        run: xcodebuild build -scheme ${{ env.scheme }} -destination name=${{ env.TVOS_SIMULATOR }}
        
      - name: Run Tests on tvOS
        run: xcodebuild clean test -scheme ${{ env.scheme }} -destination name=${{ env.TVOS_SIMULATOR }}
