name: Test

# Controls when the action will run. 
on:
  pull_request:
  
  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  scheme: AceLayout

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_on_macos:
    runs-on: macos-latest
    
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
      - uses: actions/checkout@v2
      
      - name: Build for macOS
        run: swift build
        
      - name: Run Tests on macOS
        run: swift test
        
  test_on_ios:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Tests on iOS
        run: xcodebuild clean test -scheme ${{ env.scheme }} -destination "name=iPhone 13"
        
  test_on_tvos:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run Tests on tvOS
        run: xcodebuild clean test -scheme ${{ env.scheme }} -destination "name=Apple TV"
